services:
  - type: web
    name: ai-caller-api
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port=$PORT"
